#IMPORTING THE LIBRARIES 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the dataset 

In [ ]:
dataset=pd.read_csv('/content/Iris (1).csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#Splitting the data in to training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [ ]:
print(x_train)

[[5.2 3.4 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.5 0.3]
 [4.9 2.5 4.5 1.7]
 [6.4 3.1 5.5 1.8]
 [6.  2.2 4.  1. ]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [6.5 3.  5.2 2. ]
 [4.8 3.4 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [5.8 2.8 5.1 2.4]
 [6.7 3.3 5.7 2.5]
 [7.7 3.8 6.7 2.2]
 [5.8 2.7 4.1 1. ]
 [5.7 2.6 3.5 1. ]
 [6.3 2.5 4.9 1.5]
 [6.4 2.8 5.6 2.2]
 [5.6 2.8 4.9 2. ]
 [5.5 2.6 4.4 1.2]
 [6.3 2.5 5.  1.9]
 [5.8 2.7 5.1 1.9]
 [6.4 3.2 4.5 1.5]
 [6.1 3.  4.9 1.8]
 [5.9 3.  4.2 1.5]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [5.8 2.6 4.  1.2]
 [5.4 3.  4.5 1.5]
 [6.3 2.3 4.4 1.3]
 [6.7 3.3 5.7 2.1]
 [5.7 2.8 4.1 1.3]
 [6.3 2.7 4.9 1.8]
 [5.  3.3 1.4 0.2]
 [5.8 4.  1.2 0.2]
 [7.2 3.6 6.1 2.5]
 [5.  2.3 3.3 1. ]
 [5.1 3.7 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.5 2.3 4.  1.3]
 [5.  3.6 1.4 0.2]
 [6.4 2.8 5.6 2.1]
 [6.7 3.  5.  1.7]
 [5.  3.4 1.5 0.2]
 [5.6 2.5 3.9 1.1]
 [7.3 2.9 6.3 1.8]
 [5.6 2.7 4.2 1.3]
 [4.3 3.  1.1 0.1]
 [7.2 3.2 6.  1.8]
 [6.2 3.4 5.4 2.3]
 [7.1 3.  5.

In [ ]:
print(x_test)

[[6.1 2.6 5.6 1.4]
 [6.5 3.2 5.1 2. ]
 [5.  2.  3.5 1. ]
 [5.5 2.4 3.7 1. ]
 [4.4 2.9 1.4 0.2]
 [7.6 3.  6.6 2.1]
 [6.9 3.1 5.1 2.3]
 [5.7 2.9 4.2 1.3]
 [6.  2.2 5.  1.5]
 [6.  3.4 4.5 1.6]
 [4.9 3.1 1.5 0.1]
 [4.8 3.  1.4 0.3]
 [5.7 2.8 4.5 1.3]
 [5.  3.  1.6 0.2]
 [4.4 3.  1.3 0.2]
 [6.3 2.8 5.1 1.5]
 [6.8 3.  5.5 2.1]
 [6.4 2.9 4.3 1.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [4.9 3.1 1.5 0.1]
 [6.7 3.1 4.7 1.5]
 [5.1 3.3 1.7 0.5]
 [6.1 2.9 4.7 1.4]
 [5.7 3.  4.2 1.2]
 [6.1 3.  4.6 1.4]
 [5.2 3.5 1.5 0.2]
 [5.1 3.8 1.9 0.4]
 [7.7 3.  6.1 2.3]]


#Training the navie bayes model on the datsset

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
new=classifier.predict([[5.8,2.7,5.1,1.9]])
new

array(['Iris-virginica'], dtype='<U15')

#Predicting the test set results

In [ ]:
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['Iris-versicolor' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris

#accuracy

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm= confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_pred,y_test)

[[12  0  0]
 [ 0 10  0]
 [ 0  3  5]]


0.9